#! /bin/bash

POSITIONAL_ARGS=()
RED='\033[0;31m'
NC='\033[0m' # No Color

while [[ $# -gt 0 ]]; do
  case $1 in
    -s|--source)
      SOURCE="$2"
      shift # past argument
      shift # past value
      ;;
    -o|--output)
      OUTPUT="$2"
      shift # past argument
      shift # past value
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1")
      shift
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [[ -n $1 ]]; then
    echo "Last line of file specified as non-opt/last argument:"
    tail -1 "$1"
fi

GLANG_BUILD=build/
GLANG_BIN=build/bin/glang

if [ -d ${GLANG_BUILD} ]; then
    if [ -f ${GLANG_BIN} ]; then
        ./build/bin/glang -O2 --source ${SOURCE} --output ${OUTPUT}.ll
        clang++ -lsfml-window -lsfml-system -lsfml-graphics lang/glang/lib.cc ${OUTPUT}.ll -o ${OUTPUT} 
    else
        printf "${RED}Error${NC}: glang compiler binary file not exist"
    fi
else
    printf "${RED}Error${NC}: glang build directory not exist"
fi

